version: '3.8'

services:
  ai-idea-generator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-idea-generator-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ai-idea-network

networks:
  ai-idea-network:
    driver: bridge 